Drop `laminas/laminas-zendframework-bridge` and `zendframework/*` compatibility
laminas/laminas-file pull request #9
Opened 2021-12-05 09:40 UTC by PowerKiKi

|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

Increase performance by removing a compatibility layer while **not** introducing breaking changes.

This follow the process described in details in:

https://github.com/laminas/technical-steering-committee/blob/main/meetings/minutes/2021-08-02-TSC-Minutes.md#remove-laminaslaminas-zendframework-bridge-dependency-from-our-packages

2021-12-06 02:09 UTC, Ocramius requested changes
CI failing here - unrelated to patch, but a blocker for merges, as this component is mostly security-only

2021-12-06 06:42 UTC, PowerKiKi commented
Tests should be fixed now

2021-12-08 06:58 UTC, merged

2021-12-08 06:58 UTC, Ocramius commented on test/ClassFileLocatorTest.php
> +            TestAsset\WithMethodsNamedAfterKeywords\WithReturnTypeDeclaration::class,
It's a bit of a BC break, but 🤷  - no interface change.

2021-12-08 06:59 UTC, Ocramius commented
Thanks @PowerKiKi!